### ISSUE TITLE
Support for Annotations on all types

### ISSUE THREAD

**Issue by dmitrykozinets** [zio/zio-schema#125]
Annotation support is needed on all types not just on Record.

Currently records support annotations, but it would be useful to also support annotations on all `Schema` types.

https://github.com/zio/zio-schema/blob/main/zio-schema/shared/src/main/scala/zio/schema/Schema.scala#L218

**Comment by alexvanolst** [comment]
I'd like to pick this one up.

**Comment by alexvanolst** [comment]
Other than Enum / Case is there anything left to do here? Happy to pick up the rest post hackathon if someone can point out any gaps.

**Comment by dmitrykozinets** [comment]
@alexvanolst Thank you for picking this up!
We were thinking of adding annotation on all types and doing something like this:
```
sealed trait Schema[A] {
   def annotations: Chunk[Any]
}
```
@thinkharderdev @DamianReeves what do you think?

**Comment by thinkharderdev** [comment]
Yes! I think we ultimately want to allow annotating any schema.

**Comment by DamianReeves** [comment]
Agreed

**Comment by alexvanolst** [comment]
I've opened a draft PR that gets it compiling with annotations added to the Schema trait.

Will probably need some feedback on what the desired behaviour is before it's merge-able since they don't do much right now.

**Comment by thinkharderdev** [comment]
Closed by #147
