### ISSUE TITLE
Support native schema for Map

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#138]
Currently there is no native support for maps. However, some protocols and formats have a native representation for maps (e.g. DynamoDB). Consequently, there is a strong advantage to having a native map type, distinct from `Sequence`.

 - [ ] Add new Schema.Map case class, which stores a schema for key, stores a schema for value, and extends `Schema[Map[K, V]]`.
 - [ ] Support new schema type for all existing codecs and other operations that match on schema

@thinkharderdev Contender for ZIO Hackathon??

**Comment by pierangeloc** [comment]
I'd like to work on this one

**Comment by thinkharderdev** [comment]
> I'd like to work on this one

Awesome! Let me know if you have any questions!
