### ISSUE TITLE
Support native schema for Set

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#139]
Currently there is no native support for sets. However, some protocols and formats have a native representation for sets (e.g. Redis). Consequently, there is a strong advantage to having a native set type, distinct from `Sequence`.

 - [ ] Add new Schema.Set case class, which stores a schema for element type, and extends `Schema[Set[A]]`.
 - [ ] Support new schema type for all existing codecs and other operations that match on schema

@thinkharderdev Contender for ZIO Hackathon??

**Comment by fokot** [comment]
I would like to work on this one

**Comment by zalbia** [comment]
I'd like to work on this.

**Comment by zalbia** [comment]
It looks like there's already some work in #142 that I can build on top of.

**Comment by thinkharderdev** [comment]
Closed by #173
