### ISSUE TITLE
Add schema for DynamicValue

### ISSUE THREAD

**Issue by thinkharderdev** [zio/zio-schema#162]
We should be able to use included codecs on `DynamicValue`s. This can be done by providing an implicit `Schema[DynamicValue]` in the library.

**Comment by igrebenik** [comment]
Could you be more specific about it?
Do you mean `implicit def dynamicValue[A](implicit schema: Schema[A]): Schema[DynamicValue]` on the Schema object or the implicit schema of each term of `DynamicValue` in the corresponding companion objects?

**Comment by igrebenik** [comment]
I would like to work on this
