### ISSUE TITLE
Allow pattern matching on Schema for tuples, eithers

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#18]
Tuples and eithers (products/sums) are so core to schema that we should bake them in and allow pattern matching against them, rather than encoding them atop Record / Enum.

**Comment by jdegoes** [comment]
A hint getting started:

```scala
final case class SchemaTuple2[A, B](left: Schema[A], right: Schema[B]) extends Schema[(A, B)]
final case class SchemaEither2[A, B](left: Schema[A], right: Schema[B]) extends Schema[Either[A, B]]
```

This way, if you have a `Schema[A]`, you can match against it to see if it's Tuple or Either, and then knowing this, you can extract out left / right sides as appropriate.

**Comment by sviezypan** [comment]
let me take this one
