### ISSUE TITLE
Specialize caseClass1 - caseClassN

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#2]
Currently, all the `Schema.caseClass` methods are written in terms of `Record`. This is semantically correct, but not optimally performant, because it involves packing and unpacking into maps.

To maximize performance of codecs generated with `Schema`, we should add `CaseClass` subtypes of `Schema` for various common arities of case classes (1 - 22???). Then as a convenience, we could have a method that converts these case classes to a `Schema.Record`, for cases where performance does not matter that much (e.g. `Schema.CaseClass2#toRecord`.

**Comment by thinkharderdev** [comment]
Is the idea here to have 
```
Schema.CaseClass1[A](codec: Schema[A]): Schema[A]
Schema.CaseClass2[A1,A2](codec1: Schema[A1],codec2: Schema[A2]): Schema[(A1,A2)]
...
Schema.CaseClass22[A1,...,A22](codec1: Schema[A1],...,codec22: Schema[A22]): Schema[(A1,..,A22)]
```

**Comment by jdegoes** [comment]
We need to store not just the schema for the components, but also: (1) a function that can create the target type given the pieces of its components; and (2) a function that can create the components given the target type. Of course, (1) is the case class constructor; Probably, we could simplify and for (2) because we know case classes extend `Product` and therefore we have an "unsafe" way to pull out their element types.

So something like:

```scala
Schema.CaseClass2[A1, A2, Z <: Product](codec1: Codec[A1], codec2: Codec[A2], construct: (A1, A2) => Z) extends Schema[Z]
```

And generalized, up to arity 22.

This will allow us to avoid the currently inefficient process of packing into a map / unpacking from a map.

Then with the `toRecord` method, we can convert them into the inefficient representation if desired.

**Comment by jdegoes** [comment]
@thinkharderdev Does this make sense?

**Comment by thinkharderdev** [comment]
Yeah, this seems related to #26? So something like 

```scala
trait Schema[A] {
  type Structure

  def construct(struct: Structure): A
}
```

Or should I ignore #26 until it is more fleshed out?

**Comment by jdegoes** [comment]
I would definitely ignore #26, I will probably take that one myself.

**Comment by jdegoes** [comment]
Oops, I made a mistake. We still need "field" information. 

So the example should be:

```scala
Schema.CaseClass2[A1, A2, Z <: Product](field1: (String, Codec[A1]), field2: (String, Codec[A2]), construct: (A1, A2) => Z) extends Schema[Z]
```

In fact, to force us to capture field information, we should probably do the following:

1. Make `Schema.Record` a sealed trait.
2. Rename the current `Schema.Record` to `Schema.GenericRecord`, and have it extend the new `Schema.Record`.
3. Make all the `CaseClassN` extend `Schema.Record`.

This way we have a guarantee of having field names on every record-like thing, whether that's the generic (and slow) Map-based encoding, or whether that is the much faster, specialized `CaseClassN` encoding.

The main effort of this ticket will be ensuring Magnolia derivation of `Schema` generates the more efficient `CaseClassN` encodings for case classes, and then updating the codecs.

**Comment by thinkharderdev** [comment]
Sounds good. Seems pretty straightforward.

**Comment by thinkharderdev** [comment]
@jdegoes Started looking at this one and I'm a little confused at to what the goal is (for zin-schema in general). The implementation would mostly be duplicating zio-json. Is there a particular reason that we want to have zio-schema also implement JSON and protobuf codecs from the raw schema? Why would we not just derive the codecs up-front with Magnolia? Ie. use the existing `zio.json.JsonCodec` derivation and maybe implement a `ProtobufCodec[A]` typeclass in zio-schema.

**Comment by jdegoes** [comment]
The goal is to create a schema as a first-class value, which can be manipulated without macros.

Of course, you can use Magnolia N times to create N different codes. Or you can use Magnolia 1 time to create a schema, and then from a schema, create N different codecs. In addition, a schema-as-a-value lets you write user-land code to do schema migration, documentation, and so forth, without requiring additional macro support.

If you're more interested in the motivation, I'd recommend the talk _Xenomorph_ by Kris Nuttycombe. Although this project isn't exactly that, it's designed to have similar benefits.

Ultimately, when this project is further along, I would hope that ZIO JSON would depend on ZIO Schema, and offer a codec directly, rather than the other way around. But to get there, we need to have much more robust and efficient means of generating codecs from schemas. The case class / enum tickets are a step in that direction.
