### ISSUE TITLE
Add implicit Schema[Some[A]] & change Schema[None.type] encoding

### ISSUE THREAD

**Issue by sviezypan** [zio/zio-schema#232]
I am facing currently [two problems](https://github.com/zio/zio-sql/issues/585) in ZIO SQL regarding optional schemas.

1. As Schema[A] in invariant in A, compiler does not treat Schema[Some[A]] as a related type to Schema[Option[A]]
So let's say I want to have implicitly derived schema for tuple 3 `(Some("foo"), 10, "bar")` but I am getting
`could not find implicit value for parameter x: zio.schema.Schema[(Some[String], Int, String)]`

possible solution could be to introduce implicit conversion between Option[A] to Some[A] like
```
      implicit def convertOptionToSome[A](implicit op: Schema[Option[A]]): Schema[Some[A]] =
        op.transformOrFail[Some[A]](
          {
            case Some(a) => Right(Some(a))
            case None    => Left("cannot encode Right")
          },
          someA => Right(someA)
        )
```
 
2. Schema[None.type] is encoded as 
```
 Schema[Unit].transform(_ => None, _ => ())
```
When I have a type A which is None at runtime - but I don't know yet about it - and I need to convert type A to DynamicValue, instead of DynamicValue.None I get Primitive of Unit. Also it seems that `DynamicValue.None` is not used for None but instead its used to indicate that conversion to DynamicValue failed.

One solution that came to my mind was to encode None as yet another StandardType
```
  implicit object NoneType extends StandardType[None.type] {
    override def tag                                      = Tags.NONE
    override def compare(x: None.type, y: None.type): Int = 0  
    override def defaultValue: Either[String, None.type]  = Right(None)
  }
  ```
 that way Schema[None] would be implicitly created as is the case for all the standard types. 

Conversion to DynamicValue would return
`DynamicValue.Primitive(None, StandardType.NoneType)` 
so I could easily match against a StandardType and see what value I have.

@thinkharderdev let me please know your thoughts / suggestions. If these changes make sense, I would implement them.

**Comment by thinkharderdev** [comment]
Hi @sviezypan thanks for raising this. For the first one I would just add an implicit schema for `Some[A]` so something like 

```implicit def some[A](implicit schema: Schema[A]): Schema[Some[A]] = schema.transform(Some(_), _.get)```

For None, we encode all obejects as a transform on `Schema[Unit]` but I think it makes sense to special case certain objects like `None` using `StandardType`

**Comment by sviezypan** [comment]
In the end it turned out that I needed something else so I decided to implement it on zio-sql side. Feel free to reopen if this is desired.
