### ISSUE TITLE
Get #244 merged

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#248]
**ISSUE**

A lot of additional tickets depend on the successful merging of #244, which enhances ZIO Schema with a new package, `zio.schema.validation`, which has very simple support for defining validations. Though this work is not yet complete, it is useful in its own right, and merging it will enable others to build off and extend the work.

**SOLUTION**

To solve this issue, clone the repository and grab the branch, fix all compilation errors, format the code, delete any printlns or other code not suitable for production (examples in prodution code), and ensure all tests are passing, before submitting a separate pull request that is fully ready to merge. No additional features need be added to get the work in suitable shape for merging.

**IMPACT**

This will add first-class validation support into ZIO Schema and open the way for many additional tickets.

**WHERE TO LOOK**

 - [Pull Request #244](https://github.com/zio/zio-schema/pull/244)
 - [The repo to clone / fork](https://github.com/AppleKid7/zio-schema/tree/schema-validation)

**PROBLEMATIC ISSUES**

None.

**Comment by digy** [comment]
Will work on this.

**Comment by digy** [comment]
Created a PR https://github.com/zio/zio-schema/pull/254

**Comment by jdegoes** [comment]
Fixed in #254!
