### ISSUE TITLE
Add phone number validations for strings representing US phone numbers

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#249]
**ISSUE**

There is no constructor for `zio.schema.validation.Validation` which can validate a US phone number.

**SOLUTION**

Using other constructors which already exist in `zio.schema.validation.Validation` (which include regex validation, string length checking, and numeric range checking), introduce a new constructor that satisfies the requirements of this issue.

```scala
object Validation {
  ...
  val phoneNumberUS: Validation[String] = ???
}
```

**IMPACT**

Increasing the number of constructors for `Validation` will make it far easier to use the `validation` package to 

**WHERE TO LOOK**

 - [Schema validation](https://github.com/zio/zio-schema/pull/244)

**PROBLEMATIC ISSUES**

Issue #248 must be completed first, or at least, this issue must be based off of #244.

**Comment by jadireddi** [comment]
Would like to contribute.
