### ISSUE TITLE
Consider publishing for scala 3

### ISSUE THREAD

**Issue by bilal-fazlani** [zio/zio-schema#278]

**Comment by robmwalsh** [comment]
Yes please!

**Comment by robmwalsh** [comment]
Yes please!

**Comment by tusharmath** [comment]
This is the only blocker at the moment to support more powerful route decoding features in ZIO Http.

**Comment by vigoo** [comment]
As https://github.com/zio/zio-schema/pull/243 is merged, snapshot builds should already published, for example `[0.1.9+12-6143af0b-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-schema_3/0.1.9+12-6143af0b-SNAPSHOT/`

**Comment by bilal-fazlani** [comment]
I can use [0.1.9+12-6143af0b-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-schema_3/0.1.9+12-6143af0b-SNAPSHOT/) with Scala 3, but it has a dependency on ZIO 1.

![image](https://user-images.githubusercontent.com/3396271/173177433-1323e01b-6c12-43b0-a82d-33e169cf8731.png)

Version 0.2.0-RC6 depends on ZIO 2, but is not published for Scala 3.

![image](https://user-images.githubusercontent.com/3396271/173177450-9a315d01-e6f5-41e3-b66d-6d128d68bd35.png)
