### ISSUE TITLE
Ability to extend SchemaAst with known types

### ISSUE THREAD

**Issue by vigoo** [zio/zio-schema#294]
In zio-flow `ZFlow` and `Remote` are two types with a huge schema which is used everywhere recursively so we want to avoid serializing it in case of serializing schemas (using `SemiDynamic`). (Another reason to avoid serializing it is that it is currently broken as described in https://github.com/zio/zio-flow/issues/152)

To achieve this I had to copy a lot of code from zio-schema to https://github.com/vigoo/zio-flow/blob/serialization-fixes/zio-flow/shared/src/main/scala/zio/flow/serialization/FlowSchemaAst.scala in order to have special schema AST nodes representing these types in a compact way.

It would be nice to have support for this in zio-schema itself, possibly by having some schema registry and the opt-in possibility to serialize (or do any zio-schema operations) in a contextual way so the user can provide a schema registry.

**Comment by jdegoes** [comment]
Do you want this in zio-schema 1.0?

**Comment by vigoo** [comment]
Not necessarily in 1.0, but the lack of this (or something equivalent) requires about 300 lines of code to be copied and customized in zio-flow.
