### ISSUE TITLE
Add codec for UTF Strings

### ISSUE THREAD

**Issue by anatolysergeev** [zio/zio-schema#30]
It would be useful to have simple codec that work with utf strings

**Comment by thinkharderdev** [comment]
@anatolysergeev Not sure I follow what the desired outcome is. Strings should serialized/deserialized using UTF-8 in the relevant codecs. Are you looking for a separate type which just holds the raw encoded bytes?

**Comment by anatolysergeev** [comment]
@thinkharderdev Hello, sorry for my long response. In zio-redis when we started to use zio-schema it's seems for me not very appropriate to use protobuff codec for our tests and examples, because we wanted to do it with minimal possible changes.
And I wrote our codec for that reason https://github.com/zio/zio-redis/blob/master/redis/src/main/scala/zio/redis/codec/StringUtf8Codec.scala

**Comment by thinkharderdev** [comment]
Ah, I see. So you are using the protobuf codec for serialization when storing objects in Redis but you wanted a human readable serialization format for unit tests and examples? Would the JSON codec suffice for that? The actual JSON payload should be a UTF-8 string.

**Comment by mijicd** [comment]
@thinkharderdev Sorry for not following up on the state of this issue. We currently use a "home-brewed" UTF8 string codec in our benchmarks, examples, tests, and test executor. I think it is possible to replace most of the usages with the existing codecs (e.g., JSON or protobuf codecs will be suitable for tests and examples). Once that's done, we'll need to adjust the test executor and benchmarks. The latter will probably require some implementation similar to what Anatoly mentioned to be "fair".
