### ISSUE TITLE
Add intelligent transformation of data between two schemas

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#31]
Given `Schema[A]`, and `Schema[B]`, we should be able to produce `Either[String, A => Either[String, B]]`, either alone, or with hints.

```scala
trait Schema[A] {
  ...
  def migrate[B](newSchema: Schema[B]): Either[String, A => Either[String, B]] = ???
}
```

A simple case is `Schema[B]` having smaller records and bigger enumerations, but the names of terms and relative position of structure is unchanged, in which case, the transition may always succeed.

Hints would allow more sophisticated transformations (including those requiring default values), as would an optimizer that can detect unambiguous field renames.

**Comment by girishkolantra** [comment]
Hey, this looks really interesting to me and I am going to work on this.

**Comment by thinkharderdev** [comment]
@girishkolantra this looks great so far!
