### ISSUE TITLE
There should be schema (and support as primitive) for Byte

### ISSUE THREAD

**Issue by vigoo** [zio/zio-schema#337]

**Comment by jdegoes** [comment]
To implment this ticket, see `StandardTypes` and the way other primitives are supported.

Currently there is only schema for byte chunks.

**Comment by ithinkicancode** [comment]
@jdegoes @vigoo 
Do you think this ticket is already done? https://github.com/zio/zio-schema/blob/a40e94d69d610484cb8e79a45bc1d10482034329/zio-schema/shared/src/main/scala/zio/schema/StandardType.scala#L111

**Comment by devsprint** [comment]
@jdegoes @vigoo There is support for `Byte` also in protobuf, avro, json, msg pack and thrift codecs. I think this ticket could be closed.
