### ISSUE TITLE
Add a generic data representation

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#36]
We should have a generic data representation (`Generic`) that mirrors the `Schema` hierarchy, such that we can convert an `A` and a `Schema[A]` into a `Generic`.

Something like:

```scala
sealed trait Schema[A] {
  def toGeneric(value A): Generic = ???

  def fromGeneric(generic: Generic): Either[String, A] = ???
}
```

where:

```scala
sealed trait Generic
object Generic {
  final case class Integer(value: Int) extends Generic
  final case class Record(values: Map[String, Generic]) extends Generic
  final case class Enumeration(value: (String, Generic)) extends Generic
  ...
}
```

As a law: `schema.fromGeneric(schema.toGeneric(a)) === Right(a)`.

It would be ideal (for #35) if there is an `Ordering` for `Generic`, as well as (of course) consistent equals/hashCode.

**Comment by adamgfraser** [comment]
@kitlangton and I will do this as part of Zymposium.
