### ISSUE TITLE
`DeriveSchema.gen[scala.collection.Map[K, V]]` does not work

### ISSUE THREAD

**Issue by AppleKid7** [zio/zio-schema#365]
Not sure if this would be considered a new feature or a bugfix.

Attempting to derive a schema from a Map[K,V] results on the following error:

```
Failed to derive schema for scala.collection.Map[String,zio.schema.SchemaValidationSpec.Person]. Can only derive Schema for case class or sealed trait
[error]       implicit val schema = DeriveSchema.gen[scala.collection.Map[String, Person]]
```

**Comment by jdegoes** [comment]
It should be possible to derive a schema for Scala's `Map` data type. 

This could be caused by one of two issues:

1. The implicit schema for Map not being found.
2. Some issue in the macros for schema derivation.

**Comment by devsprint** [comment]
@jdegoes, @AppleKid7 Current implementation does not provide support for macro derivation for `Map`, for scala 2.x, but only for Scala 3.  Scala 2.x macro implementation provides automatic derivation only for `sealed trait` and `case class`

However, manual derivation works fine for all supported scala version
