### ISSUE TITLE
Simplify the java.time.* StandardTypes

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#375]
Currently, [StandardType](https://github.com/zio/zio-schema/blob/main/zio-schema/shared/src/main/scala/zio/schema/StandardType.scala) defines a number of java.time.* analogues:

 - InstantType
 - LocalDateType
 - LocalTimeType
 - LocalDateTimeType
 - OffsetTimeType
 - OffsetDateTimeType
 - ZonedDateTimeType

These are defined as `case class` instead of `case object`, and as a result, they are not made `implicit`, which means that user-defined data types that utilize these `java.time.*` types cannot be derived automatically.

The reason they are `case class` is to allow them to take formatters that define a string-based format. However, while flexible, this conflates *semantic* with *encoding*, and ZIO Schema should not make any assumptions about encoding. 

This ticket is to:

1. Turn all of these data types into `case object` and make them `implicit`.
2. Update all usages of them to use a standard string-encoding, if required (e.g. by the `json` subproject).
3. Delete the `DefaultJavaTimeSchemas` trait that currently exists to work around the problem with the current encoding.

**Comment by lookingformira** [comment]
I would like to work on this issue
