### ISSUE TITLE
Implement support for @discriminatorName

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#376]
After #203 is completed, then each specified annotation may be implemented for each of the supported codecs for which it makes sense to support the annotation.

This ticket is to implement the `@discriminatorName` annotation. This annotation, which may be applied to any `sealed trait` (enumeration), means to specify the name of a field that will be used to contain the identity of the case of the enum that is being serialized.

For example, it is common in JSON to use a field named `type` to encode which case of an enum (such as `Either`) is being stored (e.g. `"typeId": "Right"` versus `"type": "Right"`.

_ZIO Schema_ already captures annotations on records and enumerations. So the main work of this ticket will be to look for the annotation `zio.schema.annotation.discriminatorName` on any sealed trait (enumeration), and then leverage it in any of the existing codecs for which it makes sense.

 - [ ] JSON Codec

**Comment by exp0nge** [comment]
I would like to work on this issue.

**Comment by exp0nge** [comment]
@jdegoes did you intend to use this also for decoding?
