### ISSUE TITLE
Implement support for @fieldDefaultValue annotation

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#385]
After #203 is completed, then each specified annotation may be implemented for each of the supported codecs for which it makes sense to support the annotation.

This ticket is to implement the `@fieldDefaultValue` annotation. This annotation, which may be applied to any field of a record (`case class`), is a marker to deserializers that if the field is not present, the specified default value should be utilized.

The main place where this new annotation should be used is in the different protocols that ZIO Schema supports. For example, the `zio-schema-json` protocol, which has serialization / deserialization in the JSON protocol.

ZIO Schema already captures annotations, so it is only necessary to look at the annotations and ensure that serialization / deserialization respects them in every protocol where the annotation makes sense.

To complete this ticket, go to all existing protocols and modify to ensure `@fieldDefaultValue` is supported in each, with a test.

**Comment by juliano** [comment]
Actually, I will start with #377

This one is free - for now
