### ISSUE TITLE
Introduce proper error hierarchy for codecs

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#387]
Currently, decoding methods in `zio.schema.codec` use a `String` for an error type, which is not sufficient to capture structured details, nor is it easily compatible with `Exception` / `Throwable`, common error types in Scala / Java.

To fix these issues, we can introduce `zio.schema.codec.DecodeError`, which is a sealed trait:

```scala
sealed trait DecodeErrorextends Exception with NoStackTrace { self =>
  def message
  override def getMessage(): String = message
  def and(that: DecodeError): DecodeError= DecodeError.And(self, that)
  def or(that: DecodeError): DecodeError= DecodeError.Or(self, that)
}
object DecodeError{
  final case class And(left: DecodeError, right: DecodeError) extends DecodeError
  final case class Or(left: DecodeError, right: DecodeError) extends DecodeError
  final case class MissingField(record: Record[_], field: Field[_], message: String) extends DecodeError
  final case class MalformedField(value: Schema[_], message: String) extends DecodeError
  final case class ReadError(cause: Cause[Any], message: String) extends DecodeError
  final case class ValidationError(validation: Validation[_], field: Field[_]) extends DecodeError
  final case class ExtraFields(fieldName: String, message: String) extends DecodeError
  ...
}
```

Then all decode methods can return `DecodingError` rather than `String`. Note that the exact subtypes of `DecodingError` should be determined by inspecting existing use cases across different protocols. The above is a guide and would likely be augmented with a few additional typed ways to fail.

**Comment by grouzen** [comment]
I was trying to make this for `JsonCodec` and found that the only way to distinguish between error types is by matching on strings, which is not very reliable. I would like to hear other opinions before starting work on it.

**Comment by devsprint** [comment]
@grouzen not sure if you are still looking to implement this change... I have submitted a PR with one solution. The Json part is very generic for now, but I'm looking to improve it without pattern matching on strings.
