### ISSUE TITLE
Increase comprehensiveness of protobuf test suite to identify & fix bugs

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#388]
The current test suite for probobuf does not include the full range of data structures that ZIO Schema supports. The test suite can be enhanced as a way of increasing the robustness of the protobuf support.

**Comment by jdegoes** [comment]
See also #286.

**Comment by olivierdeckers** [comment]
I was looking into this, but it seems all of the different schema types (primitives, product, enum, either, map, option, set, sequence, dynamic) are already being tested in various combinations. It's not clear to me what kind of enhancement we are looking for.
