### ISSUE TITLE
Ability to capture implicit typeclass instances within the schema

### ISSUE THREAD

**Issue by vigoo** [zio/zio-schema#419]
# Problem

One of the core features zio-schema provides is to derive a `Schema[A]` for a type `A` once, and then use this data type to derive the implementation of additional functionalities such as codecs. Although the schema captures many information about the type - its structure, annotations, etc. - this might not be enough customization.

Consider for example the JSON codec in zio-schema. It is implemented in a way that it takes a `Schema[A]` and converts that to a zio-json codec:

```scala
def jsonCodec[A](schema: Schema[A]): ZJsonCodec[A]
```

normally with such a typeclass + derivation based design a user expects to be able to customize the instances, for example to implement a `ZJsonCodec` for a custom type by hand but use the typeclass derivation feature for the rest of the types. In this case the expectation is that the derivation macro picks up the hand-made implicit if it is in scope and does not even build the auto-generated codec for that particular type.

Using zio-schema to implement the derivation is a great simplification but it currently does not allow the above use case - once we captured the type's schema we no longer have enough type information to summon implicits for its inner types - the place where we could do that is the macro deriving the schema itself.

It would be nice to somehow be able to ask zio-schema to summon arbitrary typeclasses automatically so they can be readily accessed from the `Schema` types as a value. 

Detailed requirements:

- It should work separately from schema derivation - a 3rd party library may have predefined schemas (maybe even hand-written like in zio-flow) that we would like to reuse
- It should be something that takes a schema and a typeclass type and somehow annotates the schema's each node with summoned typeclass instances
- Transient fields should not summon the typeclass
- Should support annotating with more then once typeclasses, an (optional) optimization can be to do it in one run

# A draft solution proposal
One possible implementation could be a similar macro to the one that derives `Schema` itself and make it summon implicits and store them in the generated schema (similar to magnolia, but following the schema derivation macro's all features such as transient fields).

To minimize the required core changes it could store the summoned implicits in the schema's existing `annotations` fields. This would also allow storing multiple implicits, by providing a `T[_] => Annotation` mapping to this macro.

There are some open questions though:
- It feels right to say this macro takes an existing schema and annotates that. But in fact it has to replicate the type level traversal of the original macro in order to get the types for each level, so probably it does not really take much advantage of the provided existing schema. 
  - What if it is modified and there is a mismatch?
  - On the other hand there are some cases especially when dealing with polymorphic types where currently we need to hand-write schema instances. I feel like passing those hand-written schemas to this summoner macro may allow it to work where the original derivation macro does not.

**Comment by jdegoes** [comment]
It seems like we could purpose this into special derivation machinery.

e.g.:

```scala
trait Deriver[F[_]] {
  def deriveRecord[A](record: Schema.Record[A], fields: => Chunk[F[A]], summoned: => Option[F[A]]): F[A]
  def deriveEnum[A](enum: Schema.Enum[A], cases: => Chunk[F[A]], summoned: => Option[F[A]]): F[A]
  def derivePrimitive[A](st: StandardType[A], summoned: => Option[F[A]]): F[A]
}

object Derive {
  def derive[F[_], A](deriver: Deriver[F])(implicit schema: Schema[A]): F[A] = ???
}
```

Such that you would do: `derive[JsonCodec, JsonCodec.deriver]` (or more useably, delegate to this invocation inside of `JsonCodec.derive[A]`).

**Comment by vigoo** [comment]
This definitely looks cleaner than what I suggested but it feels like a bigger change, requiring rewriting all the current zio-schema based derived codecs. Although that may only be the json codec for now (in zio-schema itself), and we already rewrote the other codecs (protobuf, thrift) that are directly implementing encoding and decoding to use the mutable builder/processor patterns.

**Comment by jdegoes** [comment]
Do we really have to re-write any of them? They will still work as they do now. It can be up to every implementor whether to use deriving or just schema directly.
