### ISSUE TITLE
Add support for annotations into Schema

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#45]
Using macros, we should pick up and store annotations on case classes, enumerations (sealed traits), and the individual terms that make up them (fields in case classes, cases of enumerations).

This way, without macros, users of `Schema` can peer into and alter behavior based on annotations.

**Comment by thinkharderdev** [comment]
@jdegoes Going to start work on this one. A couple of questions though:

1. Do we want to preserve the annotations when going from `CaseClassN` -> `GenericRecord` (ie when calling `CaseClassN.structure`)? I could see where we might want to hand on to them if we use the generic representation as an intermediate encoding when do migrations between case class versions. 
2. If we want to encode annotations in `GenericRecord`, should we allow them to be specified when manually constructing a `GenericRecord`

**Comment by jdegoes** [comment]
I think we want to preserve the annotations in the conversion, and because individual fields can have annotations, we'll probably need to store that data in either a tuple or a wrapper data type that stores both the schema of the field as well as its (field-specific) annotations.

**Comment by jdegoes** [comment]
I think we should allow the user to attach annotations to something constructed by hand.
