### ISSUE TITLE
Add scaladoc to codec annotations

### ISSUE THREAD

**Issue by googley42** [zio/zio-schema#478]
Issue https://github.com/zio/zio-schema/issues/203 has been implemented but it looks like there are missing scaladoc for the annotations:

> ... add and document these annotations inside zio.schema.annotation ...

**Comment by iamorozov** [comment]
I would like to try this one

**Comment by 987Nabil** [comment]
@jdegoes @vigoo actually, for Scala 3 we can extract Scala doc at macro execution. But this ticket is now already rewarded and has a merged pr. Should we open a new pr?

**Comment by vigoo** [comment]
If we can capture it it would definitely be a nice feature
