### ISSUE TITLE
Shift to use ordered maps for Schema.Record and Schema.Enumeration

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#5]
Currently, we are using a `Map` for the keys in records and enumerations, which means that we cannot rely on the key ordering. Yet for some protocols, such as grpc, the ordering is very important: it must be stable and ideally reflected by case class / subtype ordering. In order to accommodate this, we need to switch to a map type that allows linear ordering of keys. 

Scala has SortedMap, which could be used, but is not really ideal (it wants to order based on a property of the keys, but that would force us to store `(Int, String)` in the map, which is unpleasant to work with). Possibly we could use an ordinary map, together with an array that maintains key ordering; or we could create our own OrderedMap type.

**Comment by V-Lamp** [comment]
Hey, you could use [ListMap](https://www.scala-lang.org/api/current/scala/collection/immutable/ListMap.html) 
> List map iterators and traversal methods visit key-value pairs in the order they were first inserted.
