### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#50]
Add support for Scala 3.

The main issue to solve here is refactoring the macro derivation since Scala 3 macros are quite different from what is available in Scala 2. We can potentially leverage Magnolia 2.0 here but will need to investigate whether that will suffice.

**Comment by scalavision** [comment]
Any updates on this? If the build was made to support Scala 3, maybe it would be easier to do the upgrade / fill in the gaps?

**Comment by kitlangton** [comment]
I'm going to take a crack at this

**Comment by bilal-fazlani** [comment]
👀
