### ISSUE TITLE
add a codec annotation to mark a sealed trait as having all case object members

### ISSUE THREAD

**Issue by googley42** [zio/zio-schema#506]
in zio-dynamodb (which is uses zio-schema) we have the `@enumOfCaseObjects` trait level annotation to signify that all members as case objects. This gets read by our codec generation code to produce a more compact encoding that is used in many legacy databases. 

eg given this model:

```scala
sealed trait TrafficLight
case object GREEN extends TrafficLight 
case object RED extends TrafficLight
final case class Box(trafficLightColour: TrafficLight)
```
The default tagged union encoding is something like:
```
Map(trafficLightColour -> Map(String(GREEN) -> Null))
``` 
after you add the annotation to the sealed trait, the encoding is more compact, with one less level of indirection:
```scala
Map(trafficLightColour -> String(GREEN))
```

This issue is related to this one [Define a canonical set of annotations that can be applied to sealed traits, case classes, and fields](https://github.com/zio/zio-schema/issues/203)

**Comment by jdegoes** [comment]
Maybe `@SimpleEnum` to indicate all terms are `case object`s.

**Comment by andrzejressel** [comment]
Weird, then looking at schema recently I swore I've seen code like that - if everything is sealed trait is CaseObject0 it deserialises as single string. I'll take a look later.
