### ISSUE TITLE
JSON decoding failure for ADTs

### ISSUE THREAD

**Issue by bilal-fazlani** [zio/zio-schema#523]
Given an ADT and a decoding program given below

```scala
@discriminatorName("type")
sealed trait IOInteraction

object IOInteraction {
  @caseName("http")
  case class Sync(url: String) extends IOInteraction

  @caseName("kafka")
  case class Async(topic: String) extends IOInteraction

  given Schema[IOInteraction] = DeriveSchema.gen[IOInteraction]
}


@main def MainApp = {
  def decode[A: Schema](input: String) = JsonDecoder.decode(summon[Schema[A]], input)
  val result1 = decode[IOInteraction](syncStr)
  println(result1)
}
```

it works successfully with this input string:

```scala
val syncStr = """{ "type": "http" ,  "url": "http://localhost" }"""
```

but not with

```scala
val syncStr = """{ "url": "http://localhost" , "type": "http"  }"""
```

The only diff is order of discriminator field.

I am getting below error

```
Left(zio.schema.codec.DecodeError$ReadError: .url(unrecognized subtype))
```

From [discord chat](https://discord.com/channels/629491597070827530/822172415026790531/1084868104338804856)

**Comment by bilal-fazlani** [comment]
I remember a similar issue in borer some years ago

https://github.com/sirthias/borer/issues/38#issuecomment-510838882

**Comment by dpennell** [comment]
See also #529

**Comment by andrzejressel** [comment]
I think I have an idea how to do that 

/attempt #523

**Comment by jdegoes** [comment]
@runtologist All right, I trust your judgement here. 👍
