### ISSUE TITLE
JSON encoding/decoding is not symmetrical for unwrapped ADT's

### ISSUE THREAD

**Issue by dpennell** [zio/zio-schema#529]
If you encode an instance of an ADT, the discriminator field is not added to the JSON, and decoding will fail.
If you wrap the ADT instance in another case class, encoding/decoding works as expected.

See https://gist.github.com/dpennell/079a444ed01f560b115d7a18a1ea2d29 for a test case that demonstrates this.

**Comment by bilal-fazlani** [comment]
I think this is because in the failing test, schema of Choice1 is being used instead of schema of OneOf.

If you want the discriminator field to be added, you may want to use schema of parent type, i.e. OneOf. 

In the passing test it works because the type of field is parent type.

**Comment by dpennell** [comment]
> I think this is because in the failing test, schema of Choice1 is being used instead of schema of OneOf.
> 
> If you want the discriminator field to be added, you may want to use schema of parent type, i.e. OneOf.
> 
> In the passing test it works because the type of field is parent type.

You are correct.  Thanks!
