### ISSUE TITLE
Get default value from case class default paramters

### ISSUE THREAD

**Issue by liewhite** [zio/zio-schema#552]
It's very convenient to define default value in case class, and zio-json do so.

**Comment by andrzejressel** [comment]
From what I see schema does not have notion of default values for case classes.

To keep it as generic as possible I guess something like that should be added (+ support for custom deserializers like json)?

**Comment by liewhite** [comment]
> From what I see schema does not have notion of default values for case classes.

But Schema[T] is the only thing json codec can get from schema.

**Comment by liewhite** [comment]
Create instance of class can't make use of annotations.  
This is a language feature, many people use it, I think we should use default parameter as far as possible.

**Comment by 987Nabil** [comment]
I'll /attempt #552 since this this is also useful for OpenAPI gen in zio-http.
