### ISSUE TITLE
Support for custom and reserved field numbers in Protobuf codec

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-schema#575]
When schema evolves and a field is deleted, it is common to use `reserved n;` (with `n` being the deleted field number) in proto files to make sure that a given field number is not reused (which would be incompatible with existing data that has this field). It might also happen that you want a field to have a given field number for backward compatibility reasons.

A way to support that with the Protobuf codec would be great. Maybe using annotations?

**Comment by jdegoes** [comment]
/bounty $250

Perhaps `@fieldId(n: Int)` annotation can be added and supported where appropriate, such as Protobuf.

Bounty for implementation, updating Protobuf, and test suite.
