### ISSUE TITLE
Typo in string literal

### ISSUE THREAD

**Issue by andrey-shishkin** [zio/zio-schema#620]
Hi there.
Please fix "I" to "i" in "localDateTIme" :)

https://github.com/zio/zio-schema/blob/82eace0bcbe5a89fde8162ba88bd3d54dbc4e9fe/zio-schema/shared/src/main/scala/zio/schema/StandardType.scala#L49

Best Regards

**Comment by andrey-shishkin** [comment]
Hey @jdegoes . My [fix](https://github.com/zio/zio-schema/pull/632) have passed all checks, but I'm still facing WIP status in the table above. Don't know why that is.

**Comment by 987Nabil** [comment]
Fixing this will break compatibility and would need to be done in a major update. Closing this for now
