### ISSUE TITLE
Contributor's Guide page not found

### ISSUE THREAD

**Issue by c0d33ngr** [zio/zio-schema#630]
The contributor's guide link is broken
https://zio.dev/about/contributing in the README

**Comment by khajavi** [comment]
The current version of zio-sbt is outdated. After upgrading the zio-sbt-website to the latest beta version (0.4.0-alpha.22), I hope this will be fixed.

https://github.com/zio/zio-schema/blob/830017e50623936a7688746878beceb56a736aba/project/plugins.sbt#L11

**Comment by ezhil56x** [comment]
/attempt #630

<div id="algora" />

| [Algora profile](https://console.algora.io/@/ezhil56x) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ezhil56x | 9 bounties from 6 projects | <div align="center">JavaScript, HTML, <br />CSS & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clrgkne770006la0fu3uj796k/cancel-attempt) |
