### ISSUE TITLE
JSON Decoding Issue in ZIO with Order-Dependent Parsing Failure for ADT Containing Mixed Types

### ISSUE THREAD

**Issue by SHSongs** [zio/zio-schema#711]
## Description

JSON decoding bug occurs when attempting to parse parameters following a sealed trait with mixed types (case objects and a case class). The decoder fails to process any parameters that follow the ADT parameter unless the fields in the case class containing the ADT are reordered.

### Steps to Reproduce:

1. Define a sealed trait with mixed type implementations (case objects and a case class) and a discriminator. 
2. Implement a wrapper case class that includes this ADT as a parameter among other basic type parameters.
3. Use ZIO JSON to derive codecs for both the ADT and wrapper class.
4. Encode an instance of the wrapper class to JSON and decode it back to verify the integrity of all fields.

### Minimal Code to Reproduce 
```scala
import zio.schema.annotation.discriminatorName
import zio.*
import zio.json.*
import zio.schema.*

@discriminatorName("type")
sealed trait Content derives Schema

object Content {
  given JsonCodec[Content] = zio.schema.codec.JsonCodec.jsonCodec(Schema[Content])

  case object AAA extends Content
  case object BBB extends Content
  case class CCC(a: Int) extends Content
}

case class Wrapper(a: Int, c: Content, b: Boolean) derives Schema
// case class Wrapper(a: Int, b: Boolean, c: Content) derives Schema // decoding success with this order
object Wrapper {
  import Content.given

  given JsonCodec[Wrapper] = zio.schema.codec.JsonCodec.jsonCodec(Schema[Wrapper])
}

val v = Wrapper(a = 1, c = Content.AAA, b = true)
val str = v.toJson
println(s"Decoding from String: ${str.fromJson[Wrapper]}")
```

### Expected Behavior:
The decoder should reconstruct the `Wrapper` instance correctly, preserving the order and integrity of fields (a, b, c)

### Actual Behavior:
When the ADT field `c` is placed between two other fields, decoding fails for the fields that follow the ADT field. However, rearranging the fields in the `Wrapper` class (placing the ADT field at the end) resolves the issue.

### Environment:
- ZIO Schema: 1.2.2
- ZIO JSON: 0.7.1
- Scala: 3.4.2

**Comment by guersam** [comment]
It's already solved by https://github.com/zio/zio-schema/pull/710 ([scastie](https://scastie.scala-lang.org/guersam/WFIWRrtnQPy01DWEjFkIKA/4)).

The reason why it failed to decode was the bug in empty object decoding rather than the order dependency. On the contrary, there's a bug where the second `Wrapper` was being decoded successfully, because it means it didn't fully consume the input string. Related issue: https://github.com/zio/zio-schema/issues/712
