### ISSUE TITLE
Schema for non empty collections

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-schema#717]
We should support some kind of non empty collections. 
Either
1. we create a new sub type of `Collection` that takes care of the validation on construction
2. we have a method `def nonEmptyChunk[A :Schema]: Schema[NonEmptyChunk[A]]` that uses transform to validate the non-emptiness on construction

**Comment by palak2002** [comment]
> ## 💎 $250 bounty [• ZIO](https://console.algora.io/org/ZIO)
> ### Steps to solve:
> 1. **Start working**: Comment `/attempt #717` with your implementation plan
> 2. **Submit work**: Create a pull request including `/claim #717` in the PR body to claim the bounty
> 3. **Receive payment**: 100% of the bounty is received 2-5 days post-reward. [Make sure you are eligible for payouts](https://docs.algora.io/bounties/payments#supported-countries-regions)
> 
> Thank you for contributing to zio/zio-schema!
> 
> **[Add a bounty](https://console.algora.io/org/ZIO/bounties/community?fund=zio%2Fzio-schema%23717)** • **[Share on socials](https://twitter.com/intent/tweet?text=%24250+bounty%21+%F0%9F%92%8E+https%3A%2F%2Fgithub.com%2Fzio%2Fzio-schema%2Fissues%2F717&related=algoraio)**
> 
> Attempt	Started (GMT+0)	Solution
> 🟢 @nikolaiser	Aug 6, 2024, 1:36:04 PM	[#722](https://github.com/zio/zio-schema/pull/722)
> 🟢 @987Nabil		[#723](https://github.com/zio/zio-schema/pull/723)

/attempt #717
I plan to implement non-empty collections by creating a new subtype of Collection that validates non-emptiness on construction . I'll start by defining the NonEmptyCollection type and then create a corresponding Schema that enforces this validation.

**Comment by palak2002** [comment]
> ## 💎 $250 bounty [• ZIO](https://console.algora.io/org/ZIO)
> ### Steps to solve:
> 1. **Start working**: Comment `/attempt #717` with your implementation plan
> 2. **Submit work**: Create a pull request including `/claim #717` in the PR body to claim the bounty
> 3. **Receive payment**: 100% of the bounty is received 2-5 days post-reward. [Make sure you are eligible for payouts](https://docs.algora.io/bounties/payments#supported-countries-regions)
> 
> Thank you for contributing to zio/zio-schema!
> 
> **[Add a bounty](https://console.algora.io/org/ZIO/bounties/community?fund=zio%2Fzio-schema%23717)** • **[Share on socials](https://twitter.com/intent/tweet?text=%24250+bounty%21+%F0%9F%92%8E+https%3A%2F%2Fgithub.com%2Fzio%2Fzio-schema%2Fissues%2F717&related=algoraio)**
> 
> Attempt	Started (GMT+0)	Solution
> 🟢 @nikolaiser	Aug 6, 2024, 1:36:04 PM	[#722](https://github.com/zio/zio-schema/pull/722)
> 🟢 @987Nabil		[#723](https://github.com/zio/zio-schema/pull/723)

/attempt #717
I plan to implement non-empty collections by creating a new subtype of Collection that validates non-emptiness on construction (Option 1). I'll start by defining the NonEmptyCollection type and then create a corresponding Schema that enforces this validation.

**Comment by 987Nabil** [comment]
@palak2002 this is already done in my PR and it is already approved
