### ISSUE TITLE
Add `defaultValue` to Schema trait

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#74]
A `Schema#defaultValue: Either[String, A]` method can be added to the trait `Schema`, which computes a "default value" for the specified `Schema`.

e.g.:

```scala
trait Schema[A]
  def defaultValue: Either[String, A]
}
```

This default value can be computed as follows:

1. For records, compute the default value of their fields.
2. For enumerations, pick the first case.
3. For primitives, pick whatever seems natural (e.g. 0 or 0.0 or empty string).

Possibly, we can enhance this later with a `@defaultValue` annotation.

**Comment by IMax153** [comment]
I'd like to take a stab at this! 

However, I am completely new to the ZIO community (coming from the `fp-ts` community in TypeScript land) so I apologize if I have a bunch of noobie questions.

I was also hoping to get some additional direction for where to start here - after adding `defaultValue` to the `Schema` trait, what is the best place to start attempting to specify/compute the default value? 

Would it be in the [case class definitions](https://github.com/zio/zio-schema/blob/0c53a851cc5fe218cfad3d42d1078d13b228d4de/zio-schema/shared/src/main/scala/zio/schema/Schema.scala#L831) for `Schema` (i.e. `Record`, `Sequence`, etc.)?

**Comment by jdegoes** [comment]
Hi @IMax153,

In your implementation of `def defaultValue: Either[String, A]` method inside `Schema[A]`, you would pattern match on `this` / `self`, and handle each `Schema` subtype, possibly recursively. 

For a record, you have to generate default values for all the fields, and then you can use all those default values to generate a default value for the record itself.

Alternately, if you aren't as familiar with pattern matching, you could add `defaultValue: Either[String, A]` as an abstract method on `Schema[A]`, and then implement it individually for every subtype.
