### ISSUE TITLE
Implement Avro codec

### ISSUE THREAD

**Issue by thinkharderdev** [zio/zio-schema#76]
We need to implement two codecs for Avro:

1. An `AvroCodec` to serialize/deserialize the Avro binary serialization format
2. An `AvroSchemaCodec` to serialize a `Schema[A]` to an Avro JSON schema and deserialize an Avro JSON schema to a `Schema.GenericRecord`

This should be implement in a `zio-schema-avro` sub-project

**Comment by TobiasPfeifer** [comment]
I'll work on this. If anyone wants to pair on this, let me know (TobiasP on Discord)

**Comment by uurl** [comment]
I'll take this on ZIO Hackathon May 2022 (I'm rul in Discord)

**Comment by MohammadForouhesh** [comment]
Is there any update on this?

**Comment by guizmaii** [comment]
@MohammadForouhesh Weren't they made in #268?
