### ISSUE TITLE
Implement Enum4 - Enum22

### ISSUE THREAD

**Issue by thinkharderdev** [zio/zio-schema#84]
Implement sealed trait hierarchies for arity up to 22. This should extend the existing implementation for `Schema.Enum1,Schema.Enum2,Schema.Enum3` up to `Schema.Enum22` and keep `Schema.EnumN` for higher arities.

**Comment by jupposessho** [comment]
Taking this one.

**Comment by thinkharderdev** [comment]
Closed via #92
